### ISSUE TITLE
Face same issue again " Exception: Authentication failed. You have not been accepted into the beta""

### ISSUE THREAD

**Issue by TruthSearchers** [GiusTex/EdgeGPT#6] opened 2023-05-08 13:55 UTC
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 329, in init
self.struct = response.json()
File "/usr/local/lib/python3.10/dist-packages/httpx/_models.py", line 756, in json
return jsonlib.loads(self.text, **kwargs)
File "/usr/lib/python3.10/json/init.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 399, in run_predict
output = await app.get_blocks().process_api(
File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1299, in process_api
result = await self.call_function(
File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1036, in call_function
prediction = await anyio.to_thread.run_sync(
File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
return await future
File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
result = context.run(func, *args)
File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 488, in async_iteration
return next(iterator)
File "/content/drive/.shortcut-targets-by-id/1-aH56S1YRqDNMZxOYbQG7vIqxXro3ZRl/text-generation-webui/modules/chat.py", line 247, in cai_chatbot_wrapper
for history in chatbot_wrapper(text, state):
File "/content/drive/.shortcut-targets-by-id/1-aH56S1YRqDNMZxOYbQG7vIqxXro3ZRl/text-generation-webui/modules/chat.py", line 174, in chatbot_wrapper
prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
File "/content/drive/.shortcut-targets-by-id/1-aH56S1YRqDNMZxOYbQG7vIqxXro3ZRl/text-generation-webui/modules/extensions.py", line 94, in apply_extensions
return EXTENSION_MAP[typ](*args, **kwargs)
File "/content/drive/.shortcut-targets-by-id/1-aH56S1YRqDNMZxOYbQG7vIqxXro3ZRl/text-generation-webui/modules/extensions.py", line 69, in _apply_custom_generate_chat_prompt
return custom_generate_chat_prompt(text, state, **kwargs)
File "/content/drive/.shortcut-targets-by-id/1-aH56S1YRqDNMZxOYbQG7vIqxXro3ZRl/text-generation-webui/extensions/EdgeGPT/script.py", line 168, in custom_generate_chat_prompt
asyncio.run(EdgeGPT())
File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/content/drive/.shortcut-targets-by-id/1-aH56S1YRqDNMZxOYbQG7vIqxXro3ZRl/text-generation-webui/extensions/EdgeGPT/script.py", line 156, in EdgeGPT
bot = Chatbot(cookie_path='extensions/EdgeGPT/cookies.json')
File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 583, in init
_Conversation(self.cookies, self.proxy),
File "/usr/local/lib/python3.10/dist-packages/EdgeGPT.py", line 331, in init
raise Exception(
Exception: Authentication failed. You have not been accepted into the beta

It was working well till yesterday and suddenly face this issue this morning tried to run again and again multiple times but same issue then i try to change cookie still same issue

**Comment by GiusTex** [comment] 2023-05-08 15:21
And you can still use normal Bing ? I suppose so, if you could until now, uhm

**Comment by TruthSearchers** [comment] 2023-05-08 15:23
Yeah it is don't able to understand

**Comment by GiusTex** [comment] 2023-05-08 15:29
Your error could be caused by this:
````
File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:
...your error
````
I'll look into it too

**Comment by GiusTex** [comment] 2023-05-08 16:48
- How did you install the webui ? (An old and working one-click installer, manually cloning the repo and installing dependencies with Conda, ecc...)
- Do you start the webui with some arguments? (From the old "start-webui.bat", or from the python script)
- Are you using other extensions, do they work, does EdgeGPT work without them?

I updated the webui (I'm using an old version built with a one-click installer), and it works for me, you must have something different from my setup, maybe in the questions above

**Comment by TruthSearchers** [comment] 2023-05-08 17:05
I updated to latest version of web ui on colab and run from python script
I am using other extensions too they working fine with edgegpt before 
One extra change i did is upgrading the protobuf from 3.19.6 to 3.20.3 because webui suddenly not supporting that version
All are working well

**Comment by GiusTex** [comment] 2023-05-08 17:45
If you have space on your disk can you install again in a new folder the webui? I managed to do it, there are some different things (like: `INFO:HTTP Request: GET https://edgeservices.bing.com/edgesvc/turing/conversation/create "HTTP/1.1 200 OK"`) but EdgeGPT continue working for me. If you can but have errors write here, probably are missing dependencies, like me

**Comment by TruthSearchers** [comment] 2023-05-08 17:51
I don't think that's the problem because yesterday also in console it's info:http request  one

In argument it's --chat

**Comment by TruthSearchers** [comment] 2023-05-08 18:09
So now i noticed it only replying 1 message after that same this error haha whats happening

**Comment by GiusTex** [comment] 2023-05-08 20:42
Just in case, `git pull` this extension to update the script (no more cookies required) and open cmd_windows.bat and run `pip install EdgeGPT` and `conda list EdgeGPT` to see if your version is >= 0.3.6 (later versions don't need anymore the cookies)

**Comment by TruthSearchers** [comment] 2023-05-09 05:26
It's working now and didn't change anything haha what happened to it 
What causing this error bro sometimes

**Comment by GiusTex** [comment] 2023-05-09 09:51
> Your error could be caused by this:
> 
> ```
> File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> The above exception was the direct cause of the following exception:
> ...your error
> ```
> 
> I'll look into it too

As I said here, I think that's the main error, it's a the top of your error log (12th line), I searched yesterday the `Expecting value: line 1 column 1 (char 0)` error and I found something [here](https://github.com/acheong08/EdgeGPT/issues?q=sort%3Aupdated-desc+Expecting+value%3A+line+1+column+1+%28char+0%29) but yesterday couldn't fix it; I think I will stop for now and close the issue, cause I don't know if what I tell you is working since you don't have the error, if you have the same problem open again this issue

**Closed** 2023-05-09 09:52 UTC
